### ISSUE TITLE
Print stack traces

### ISSUE THREAD

**Issue by MylesBorins** [jstime/jstime#13]
Currently there are no stack traces being printed... it would be nice to have them

**Comment by EstebanBorai** [comment]
Hello @MylesBorins !
I would like to work on this issue!

**Comment by MylesBorins** [comment]
That would be awesome!

I'm on mobile right now but I'll follow up in a bit with some notes about where the current error handling is implemented and a pointer to the stack trace code in deno

As a heads up my understanding is that stack traces are pretty gnarly to get working.

A smaller scoped project might be printing file name + and line number

**Comment by EstebanBorai** [comment]
@MylesBorins awesome!

Okey I just did the following:

```
Error: me throwing so bad!
    at meThrow (<anonymous>:6:9)
    at willThrowInTheFuture (<anonymous>:2:3)
    at <anonymous>:9:1
```

Where the JS file is:

```javascript
function willThrowInTheFuture() {
  meThrow();
}

function meThrow() {
  throw new Error('me throwing so bad!');
}

willThrowInTheFuture();
```

Any thoughts?

**Comment by MylesBorins** [comment]
@EstebanBorai that's an awesome first step!

I think if we instantiate the scope with the file name we'll get the file name instead of anonymous

**Comment by EstebanBorai** [comment]
Sure! @MylesBorins , let me check!

**Comment by EstebanBorai** [comment]
Okey, we have it!
But theres a lot of values that I need now!

With the file I show you before, this is the current output:

```
Error: me throwing so bad!
    at meThrow (test.js:10:9)
    at willThrowInTheFuture (test.js:6:3)
    at test.js:13:1
```

The thing is that we need a `ScriptOrigin` instance which has so many arguments!

Im mocking most of these values but I still have to find a way to get the others!

**Comment by MylesBorins** [comment]
I think we can set

is_wasm: false
script_id: ?
resource_is_shared_cross_origin: false
source_map_url: none
resource_is_opaque: ?
is_module: false (for now, really want to get module loader working but it's an entirely different hairy beast)

**Comment by MylesBorins** [comment]
btw you may need to rebase against main because I had to do some force pushing eeeek
